version: "2"

services:
# Setup ambari cluster
  ambarim:
    image: ambari_master
    container_name: ambarim.cubis
    privileged: true
    hostname: ambarim.cubis
    ports:
      - 4040:4040
      - 7860:7860
      - 8080:8080
      - 8088:8088
      - 8500:8500
      - 9099:9099
      - 9225:9225
      - 18080:18080
      - 31015:31015
      - 50070:50070
      - 56000-56500:56000-56500
    entrypoint: /root/bootstrap.sh
    dns:
      - 10.104.1.11
      - 8.8.8.8
    networks:
      - nw
  ambaris:
    image: ambari_agent
    container_name: ambaris.cubis
    hostname: ambaris.cubis
    entrypoint: /root/bootstrap.sh
    ports:
      - 10000:10000
    dns:
      - 10.104.1.11
      - 8.8.8.8
    networks:
      - nw
  ambaria1:
    image: ambari_agent
    container_name: ambaria1.cubis
    hostname: ambaria1.cubis
    entrypoint: /root/bootstrap.sh
    dns:
      - 10.104.1.11
      - 8.8.8.8
    networks:
      - nw
  ambaria2:
    image: ambari_agent
    container_name: ambaria2.cubis
    hostname: ambaria2.cubis
    entrypoint: /root/bootstrap.sh
    dns:
      - 10.104.1.11
      - 8.8.8.8
    networks:
      - nw
      
# Setup a bridge custom network for network referencing through name resolution
# This is not supported by the default bridge
networks:
  nw:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
